# Workflow Publish
name: Publish

on:
  workflow_dispatch

# if granular access token is replaced with Trusted Publishing (does not work)
#permissions:
#  id-token: write  # Required for OIDC
#  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm (without this step, the authorization for "npm publish" does not work)
      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false   # prevent recursive install (creating node_modules in template/frontend, template/backend)

      # Install only the package you want to publish
      - name: Install dependencies for project
        run: pnpm install

      - name: Publish package on NPM
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}